name: rxdart_ext_example
description: rxdart_ext_example
publish_to: none
version: 0.2.9

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  rxdart_ext: any
  rxdart: ^0.28.0-dev.0
  dart_either: ^1.0.0
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.1

dependency_overrides:
  rxdart_ext:
    path: ../../rxdart_ext
