name: rxdart_ext
description: Some extension methods and classes built on top of RxDart - RxDart extension.
version: 0.1.1-dev.0
author: Petrus Nguyen Thai Hoc <hoc081098@gmail.com>
homepage: https://github.com/hoc081098/rxdart_ext.git
repository: https://github.com/hoc081098/rxdart_ext.git
issue_tracker: https://github.com/hoc081098/rxdart_ext/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  rxdart: ^0.27.0
  meta: ^1.3.0
  stack_trace: ^1.10.0
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4
  collection: ^1.15.0
  mockito: ^5.0.7
  build_runner: ^2.0.2
  dart_either: ^0.0.1

#  pub run build_runner build --delete-conflicting-outputs