name: rxdart_ext
description: Some extension methods and classes built on top of RxDart - RxDart extension.
version: 0.1.2
homepage: https://github.com/hoc081098/rxdart_ext.git
repository: https://github.com/hoc081098/rxdart_ext.git
issue_tracker: https://github.com/hoc081098/rxdart_ext/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  rxdart: ^0.27.2
  meta: ^1.7.0
  stack_trace: ^1.10.0
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.12
  collection: ^1.15.0
  quiver: ^3.0.1
  mockito: ^5.0.15
  build_runner: ^2.1.2
  dart_either: ^0.0.1

#  pub run build_runner build --delete-conflicting-outputs