name: rxdart_ext
description: Some extension methods and classes built on top of RxDart - RxDart extension.
version: 0.2.7-dev.0
homepage: https://github.com/hoc081098/rxdart_ext.git
repository: https://github.com/hoc081098/rxdart_ext.git
issue_tracker: https://github.com/hoc081098/rxdart_ext/issues
funding:
  - https://www.buymeacoffee.com/hoc081098

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  rxdart: ^0.27.5
  meta: ^1.7.0
  stack_trace: ^1.10.0
  path: ^1.8.0
  dart_either: ^1.0.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.12
  collection: ^1.16.0
  quiver: ^3.1.0
  mockito: ^5.2.0
  build_runner: ^2.1.2
  built_collection: ^5.1.1
  tuple: ^2.0.0

#  pub run build_runner build --delete-conflicting-outputs
dependency_overrides:
  rxdart: 0.0.2
