name: rxdart_ext
description: Some extension methods and classes built on top of RxDart - RxDart extension.
version: 0.0.1
author: Petrus Nguyen Thai Hoc <hoc081098@gmail.com>
homepage: https://github.com/hoc081098/rxdart_ext.git
repository: https://github.com/hoc081098/rxdart_ext.git
issue_tracker: https://github.com/hoc081098/rxdart_ext/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  rxdart: ^0.26.0
  meta: ^1.3.0
  stack_trace: ^1.10.0
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  collection: ^1.15.0
  mockito: ^5.0.3
  build_runner: ^1.12.2

#  pub run build_runner build --delete-conflicting-outputs